version: '3'
services:
  ui:
    image: devopsbyexample/contacts-ui
    ports:
      - "8080:80"
    depends_on:
      - api
    environment:
      - API_HOST=api
      - API_PORT=3000
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      - DB_HOSTNAME=db
      - DB_NAME=contacts
      - DB_USERNAME=test
      - DB_PASSWORD=test
    command: dockerize -timeout 20s -wait tcp://db:5432 npm start
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=contacts
